/// Flutter icons Quipu
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Quipu
///      fonts:
///       - asset: fonts/Quipu.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Quipu {
  Quipu._();

  static const _kFontFam = 'Quipu';
  static const String? _kFontPkg = null;

  static const IconData isotipo = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
